backend:
  name: github
  repo: MadeByMike/madebymike.github.io 
  branch: hugo
media_folder: "site/static/img/uploads"
public_folder: "/images/img/uploads"
collections:
  - name: "writing"
    label: "Post"
    folder: "writing"
    fields:
      - {label: "Language", name: "language"}